export const GET_LINKS_REQUEST = 'GET_LINKS_REQUEST';
export const GET_LINKS_SUCCESS = 'GET_LINKS_SUCCESS';
export const CREATE_SESSION = 'CREATE_SESSION';
export const DESTROY_SESSION = 'DESTROY_SESSION';
export const FAIL_LINKS_REQUEST = 'FAIL_LINKS_REQUEST';
export const FAIL_REGISTRATION = 'FAIL_REGISTRATION';
export const FAIL_LOGIN = 'FAIL_LOGIN';
export const FAIL_LOGOUT = 'FAIL_LOGOUT';
